{
 "title": "演示面板",
 "time": { "from": "2021-02-19T16:00:00.000Z", "to": "2021-02-20T15:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(prometheus_demo_request_total{application=\"$application\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "内存数据", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Direct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "prometheus_demo_memory_usage_bytes{application=\"$application\",instance=\"$instance\",type=\"direct\"}",
     "legendFormat": "direct"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "prometheus_demo_memory_usage_bytes{application=\"$application\",instance=\"$instance\",type=\"heap\"}",
     "legendFormat": "heap"
    }
   ]
  },
  { "title": "请求数据", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "请求延迟直方图",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "prometheus_demo_request_latency_histogram_bucket{application=\"$application\",instance=\"$instance\"}",
     "legendFormat": "分布 le={{le}} {{url}}"
    }
   ]
  },
  {
   "title": "请求延迟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_demo_request_latency{application=\"$application\",instance=\"$instance\"}",
     "legendFormat": "分位 quantile={{quantile}} {{url}}"
    }
   ]
  },
  {
   "title": "请求总数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_demo_request_total{application=\"$application\",instance=\"$instance\"}",
     "legendFormat": "url {{url}}"
    }
   ]
  }
 ]
}